# nfpm configuration file used as template.
# all "ig_" will be replaced by proper values in the release pipeline.
name: "ig"
arch: "ig_arch"
platform: "linux"
version: "ig_version"
section: "devel"
replaces:
- ig
provides:
- ig
maintainer: "Francis Laniel <flaniel@linux.microsoft.com>"
description: |
  Introspecting and debugging Kubernetes applications using eBPF "gadgets"
vendor: "Inspektor Gadget"
homepage: "https://www.inspektor-gadget.io/"
license: "Apache"
contents:
- src: ig_path
  dst: /usr/bin/ig
