name: "Set CONTAINER_REPO to environment"
description: "CONTAINER_REPO will be set as inputs.registry/inputs.container-image, if inputs.container-image-ci is not set.
  If inputs.container-image-ci is set, CONTAINER_REPO will be set to inputs.registry/inputs.container-image if current branch is main or tag, otherwise to inputs.registry/inputs.container-image-ci"

inputs:
  registry:
    description: "Registry where to push container image"
    required: true
  container-image:
    description: "The name of the container image"
    required: true
  container-image-ci:
    description: "The name of the container image used for CI"

runs:
  using: "composite"
  steps:
    - name: Set CONTAINER_REPO
      shell: bash
      run: |
        if [ -z '${{ inputs.registry }}' ]; then
          echo 'inputs.registry should not be empty! Set it before calling this action'

          exit 1
        fi

        if [ -z '${{ inputs.container-image }}' ]; then
          echo 'inputs.container-image should not both be empty! Set it before calling this action'

          exit 1
        fi

        # inputs.container-image-ci is set, use github.ref to choose between them.
        if [ -n '${{ inputs.container-image-ci }}' ]; then
          if [[ ${{ github.ref }} == 'refs/heads/main' || ${{ github.ref }} == 'refs/tags/v'* ]]; then
            container_image='${{ inputs.container-image }}'
          else
            container_image='${{ inputs.container-image-ci }}'
          fi
        else # Only inputs.container-image is set, use it.
          container_image='${{ inputs.container-image }}'
        fi

        echo CONTAINER_REPO="${{ inputs.registry }}/${container_image}" >> $GITHUB_ENV
